enabled: true
auto: true
commit_template: |
  Restyled by ${restyler.name}
pull_requests: true
statuses:
  skipped: true         # Green when skipped
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
request_review: author
image: 'restyled/restyler-autopep8:v2.0.0'
command:
  - autopep8
  - '--in-place'
arguments: []
include:
  - '**/*.py'
interpreters:
  - python